### ISSUE TITLE
Cannot launch frontend app

### ISSUE THREAD

**Issue by lucianosilva44** [IBM/PublicRegulationFabric-Food-IBPV20#4]
Hello,

When trying to launch the web-app frontend application, I got this:

This relative module was not found:

* ./dist/json-tree.css in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&

What module is this? Do anyone knows?

**Comment by kkbankol-ibm** [comment]
resolved offline

**Comment by hieulinh1997** [comment]
> resolved offline

anh có thể nói cụ thể hơn? thanks

**Comment by kkbankol-ibm** [comment]
hello @hieulinh1997, we resolved the issue by adding the `dist` folder, which has the missing css/js files.

so you can fix the issue by either pulling the latest from this repo, or generate your own build files by running the following
```
cd frontend
npm run build
```
